In [61]:
from collections import Counter
import re
import os,sys
import pandas as pd
import numpy as np

## Definição de variaveis de ambiente

In [50]:
user_path = os.environ.get('USERPROFILE')
path_dir = user_path+'\\Documents\\Consultoria\\dataset'
nan_value = float("NaN")

## Geração do dicionário

In [3]:
df_index = pd.DataFrame([['','']],columns=['doc','word_ids'])
word_dic = pd.read_csv(user_path+'\\Documents\\Consultoria\\word_dic.csv')

In [4]:
#word_dic = pd.Series(word_dic.c1)
#word_dic = word_dic.to_dict('series')
word_dic = dict(zip(word_dic.c1, word_dic.word_id))
#word_dic

## Iniciando Data Frame do Index

In [250]:
doc_df = pd.DataFrame([['','']],columns=['word_id','doc_num'])

for filename in os.listdir(path_dir):
    #print(filename)    
    filepath = path_dir+'\\'+filename   
    with open(filepath) as fp:
        #Lê texto convertendo em lowercase para facilitar a ordenação
        text = fp.read().lower()
        #quebra o texto em palavras
        words = re.split(r"\W+", text) 
        #cria uma série com as palavras
        word_series = pd.Series(data=words)        
        #faz o de-para com os ID do dicionário gerado no script anterior
        word_series = word_series.map(word_dic.get)
        #remove registros que não estão no dicionario (stop words)
        word_series = word_series.dropna()
        #converte para dataFrame
        word_df = pd.DataFrame(word_series)
        #renomeia coluna
        word_df = word_df.rename(columns={0:'word_id'})
        #remove palavras duplicadas
        word_df = word_df.drop_duplicates(subset=['word_id'])                
        #ordena as palavras pelo id
        word_df = word_df.sort_values(by='word_id')        
        #adiciona coluna doc_num com o nome do arquivo
        word_df['doc_num'] = int(filename)              
        #word_df = word_df.dropna(inplace=True)
        #incrementa o dataFrame de palavras e documentos
        doc_df = doc_df.append(word_df)        
        #break
    #break
#word_df = word_df.drop_duplicates(subset=['doc_num'])
#Converve vazio para NaN
doc_df.replace('', np.nan, inplace=True)
#doc_df['word_id'] = doc_df['word_id'].astype(str).int(doc_df['word_id'])
#Remove NaN
doc_df.dropna(inplace=True)
#Remove decimal
doc_df = doc_df.round(decimals=0).astype('int')
#doc_df = doc_df.word_id.astype('object')
#doc_df.word_id.astype(str).replace('\.0','')
#ordena docNum para Indice
doc_df = doc_df.sort_values(by='doc_num')
#Cria o Indice
doc_df = doc_df.groupby('word_id')['doc_num'].apply(list).reset_index(name='doc_num')
#doc_df
#Gera CSV com o indice
doc_df.to_csv(path_or_buf=user_path+'\\Documents\\Consultoria\\doc_df.csv',
                     index=False, sep=';')

In [249]:
#doc_df
#word_df
#word_dic
#word_series

       word_id                                            doc_num
0            0                                               [21]
1            1                                           [14, 41]
2            2                                                [8]
3            3                                               [27]
4            4                                           [30, 34]
5            5                                               [27]
6            6                   [0, 1, 3, 9, 12, 19, 20, 22, 44]
7            7                                                [0]
8            8                                                [9]
9            9  [2, 4, 11, 12, 13, 15, 16, 17, 31, 32, 33, 41,...
10          10                                               [23]
11          11                                                [9]
12          12                                            [4, 43]
13          13                                            [2, 44]
14          14  [0, 1, 2, 3, 4, 6, 8, 9, 11, 12, 15, 16, 17, 1...
15          15  [0, 1, 2, 3, 4, 6, 9, 11, 12, 15, 16, 17, 18, ...
16          16      [1, 3, 8, 10, 11, 17, 21, 26, 27, 30, 31, 33]
17          17  [2, 5, 6, 12, 21, 22, 23, 24, 30, 32, 33, 41, ...
18          18                                                [1]
19          19                                               [14]
20          20                                                [9]
21          21                                                [0]
22          22                                     [2, 3, 12, 31]
23          23               [1, 2, 3, 5, 11, 19, 31, 37, 41, 44]
24          24                                   [11, 12, 13, 34]
25          25              [2, 3, 9, 11, 12, 15, 33, 41, 43, 44]
26          26                                               [43]
27          27                    [0, 1, 3, 8, 9, 12, 17, 19, 20]
28          28         [0, 1, 2, 3, 4, 9, 12, 15, 31, 32, 34, 43]
29          29                                  [0, 8, 9, 15, 32]
...        ...                                                ...
88943    89316                                               [30]
88944    89317                                           [18, 21]
88945    89318                                                [8]
88946    89319                                                [8]
88947    89320                                                [2]
88948    89322                                                [2]
88949    89323                                                [3]
88950    89324                                            [2, 18]
88951    89325                                       [18, 21, 40]
88952    89326                                               [21]
88953    89327                                               [21]
88954    89328                                     [6, 8, 18, 21]
88955    89329                                         [1, 3, 21]
88956    89330                                               [30]
88957    89331                                               [21]
88958    89332                                               [21]
88959    89333                                                [0]
88960    89334                                               [15]
88961    89335                                               [18]
88962    89336                                               [21]
88963    89337                                                [3]
88964    89338                                                [3]
88965    89339                                         [1, 3, 21]
88966    89340                                               [21]
88967    89341                                               [21]
88968    89342                                               [21]
88969    89343                                               [21]
88970    89344                                               [18]
88971    89345                                               [18]
88972    89346                                                [2]

[88973 rows x 2 columns]